#!/bin/bash
#
# Copyright (C) 2017 Jonathan Rajotte-Julien <jonathan.rajotte-julien@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../

TMPDIR=$(mktemp -d)

#This is needed since the testpoint create a pipe with the consumerd type suffixed
TESTPOINT_BASE_PATH=$(readlink -f "$TMPDIR/lttng.t_p_n")
TESTPOINT_PIPE_PATH=$(mktemp -u "${TESTPOINT_BASE_PATH}.XXXXXX")
TESTPOINT=$(readlink -f ${CURDIR}/.libs/libpause_consumer.so)


TESTAPP_PATH="$TESTDIR/utils/testapp"

GEN_UST_EVENTS_TESTAPP_NAME="gen-ust-events"
GEN_UST_EVENTS_TESTAPP_BIN="$TESTAPP_PATH/$GEN_UST_EVENTS_TESTAPP_NAME/$GEN_UST_EVENTS_TESTAPP_NAME"

GEN_UST_NEVENTS_TESTAPP_NAME="gen-ust-nevents"
GEN_UST_NEVENTS_TESTAPP_BIN="$TESTAPP_PATH/$GEN_UST_NEVENTS_TESTAPP_NAME/$GEN_UST_NEVENTS_TESTAPP_NAME"

TESTAPP_STATE_PATH=$(mktemp -u "$TMPDIR/application_state.XXXXXXXXXX")

NR_ITER=5
NR_USEC_WAIT=5

SESSION_NAME="my_session"
CHANNEL_NAME="my_channel"

TRACE_PATH=$(mktemp -d)
PAGE_SIZE=$(getconf PAGE_SIZE)

DIR=$(readlink -f $TESTDIR)


source $TESTDIR/utils/utils.sh
source $CURDIR/util_event_generator.sh

function test_event_rule_condition_exclusion_notification
{
	ust_event_generator_run_once_per_transition "$GEN_UST_NEVENTS_TESTAPP_BIN" "$TESTAPP_STATE_PATH" 5 5 &
	APP_PID=$!

	$CURDIR/notification 3 LTTNG_DOMAIN_UST $APP_PID $TESTAPP_STATE_PATH

	kill -SIGUSR2 $APP_PID
	wait $APP_PID 2> /dev/null
}

LTTNG_SESSIOND_ENV_VARS="LTTNG_TESTPOINT_ENABLE=1 CONSUMER_PAUSE_PIPE_PATH=${TESTPOINT_PIPE_PATH} LD_PRELOAD=${TESTPOINT}"
start_lttng_sessiond_notap

test_event_rule_condition_exclusion_notification

stop_lttng_sessiond_notap

rm -rf $TMPDIR
