#!/bin/bash
#
# Copyright (C) - 2017 Jérémie Galarneau <jeremie.galarneau@efficios.com>
#
# This library is free software; you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation; version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

CURDIR=$(dirname $0)/
TESTDIR=$CURDIR/../../../

TESTAPP_PATH="$TESTDIR/utils/testapp"
TESTAPP_NAME="gen-ust-events"
TESTAPP_BIN="$TESTAPP_PATH/$TESTAPP_NAME/$TESTAPP_NAME"

SESSION_NAME="my_session"
EVENT_NAME="tp:tptest"

TEMP_PATH=$(mktemp -d)
ROTATION_CLIENT_PIPE_NAME="rotation_client_pipe"
ROTATION_CLIENT_PIPE_PATH="$TEMP_PATH/$ROTATION_CLIENT_PIPE_NAME"
PAGE_SIZE=$(getconf PAGE_SIZE)
SUBBUF_SIZE=$(expr $PAGE_SIZE \* 8)

FILE_SYNC_AFTER_TRIGGER_SETUP=$(mktemp -u)
FILE_SYNC_AFTER_FIRST_EVENT=$(mktemp -u)

NR_ITER=-1
NR_USEC_WAIT=5

DIR=$(readlink -f $TESTDIR)

source $TESTDIR/utils/utils.sh
start_lttng_sessiond_notap

create_lttng_session_notap $SESSION_NAME $TEMP_PATH

enable_ust_lttng_channel_notap $SESSION_NAME $CHANNEL_NAME --subbuf-size=$SUBBUF_SIZE
enable_ust_lttng_event_notap $SESSION_NAME $EVENT_NAME $CHANNEL_NAME

$TESTAPP_BIN $NR_ITER $NR_USEC_WAIT $FILE_SYNC_AFTER_FIRST_EVENT &
APP_PID=$!

while [ ! -f "${FILE_SYNC_AFTER_FIRST_EVENT}" ]; do
	sleep 0.5
done

mkfifo $ROTATION_CLIENT_PIPE_PATH
if [ $? -ne 0 ]; then
	diag "Failed to create rotation client pipe at $ROTATION_CLIENT_PIPE_PATH"
fi

# The rotation notification client will setup the rotation triggers and
# subscribe to their notifications. Once that setup is in place, a sync
# file will be created which signals that we can proceed.
$CURDIR/rotation $SESSION_NAME $FILE_SYNC_AFTER_TRIGGER_SETUP > $ROTATION_CLIENT_PIPE_PATH &
ROTATION_CLIENT_PID=$!

while [ ! -f "${FILE_SYNC_AFTER_TRIGGER_SETUP}" ]; do
	sleep 0.5
	echo "Waiting for trigger setup... file path: $FILE_SYNC_AFTER_TRIGGER_SETUP"
done

kill -9 $TAIL_PID
wait $TAIL_PID 2> /dev/null

echo "saluuuut"

while read line
do
	echo "HO HO HO $line"
done < $ROTATION_CLIENT_PIPE_PATH

stop_lttng_sessiond_notap

# On ungraceful kill the app is cleaned up via the full_cleanup call
# Suppress kill message
kill -9 $APP_PID
wait $APP_PID 2> /dev/null

rm -rf $TEMP_PATH
rm $FILE_SYNC_AFTER_TRIGGER_SETUP
rm $ROTATION_CLIENT_PIPE_PATH
rm ${consumerd_pipe[@]} 2> /dev/null
